//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Poineet
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AttendanceTransaction
    {
        public int ID { get; set; }
        public int Employeeid { get; set; }
        
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> TodayDateTrans { get; set; }
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> AttendTime { get; set; }
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> leaveTime { get; set; }
        public Nullable<int> minus { get; set; }
        public Nullable<int> bonus { get; set; }
        public Nullable<decimal> netsalary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
