//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Poineet
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AttendanceTransactions = new HashSet<AttendanceTransaction>();
        }
    
        public int Empolyee_ID { get; set; }
        public string Employee_Name { get; set; }
        public decimal Employee_Salary { get; set; }
        [DataType(DataType.Time)]
        public System.DateTime Attend_Time { get; set; }
        [DataType(DataType.Time)]
        public System.DateTime Leave_Time { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Date_Of_Hiring { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceTransaction> AttendanceTransactions { get; set; }
    }
}
