//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Details
    {
        public int ID { get; set; }
        public int Head_ID { get; set; }
        public int Item_iD { get; set; }
        public int Qtn { get; set; }
        public decimal Price { get; set; }
        public decimal Total { get; set; }
        public int Unit { get; set; }
    
        public virtual Bill_Head Bill_Head { get; set; }
        public virtual ItemsTable ItemsTable { get; set; }
    }
}
