//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stores
{
    using stores.Controllers;
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemsTable()
        {
            this.Bill_Details = new HashSet<Bill_Details>();
            this.ItemUnitsTables = new HashSet<ItemUnitsTable>();
            this.Stockes = new HashSet<Stocke>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal SellPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Details> Bill_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemUnitsTable> ItemUnitsTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stocke> Stockes { get; set; }
        //public virtual ICollection<SalseInvoice> SalseInvoice { get; set; }
    }
}
