//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocke
    {
        public int ID { get; set; }
        public int Store_ID { get; set; }
        public int Item_ID { get; set; }
        public int Quantity { get; set; }
    
        public virtual ItemsTable ItemsTable { get; set; }
        public virtual StoresTable StoresTable { get; set; }
    }
}
