//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AppConfiguration
    {
        public int Id { get; set; }
        public int MinusMoney { get; set; }
        public int BonusMoney { get; set; }
        public int AbsnceMoney { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime DateConfig { get; set; }
        public int EmpId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
