//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AttendanceTransaction
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> TodayDateTrans { get; set; }
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> AttendTime { get; set; }
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> LeaveTime { get; set; }
        public Nullable<int> minus { get; set; }
        public Nullable<int> bonus { get; set; }
        public string Attend { get; set; }
        public List<Attend> Attends { get; set; }

        public virtual Employee Employee { get; set; }
    }
}
