CREATE DATABASE Project_ITI
ON(
NAME=mainFile,
FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.SHALABYSQL\MSSQL\DATA\mainFile.mdf',
SIZE=30,
FILEGROWTH=5,
MAXSIZE=50
),
FILEGROUP FILEGROUP1 (
NAME=SecondaryFile,
FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.SHALABYSQL\MSSQL\DATA\SecondaryFile.ndf',
SIZE=30,
FILEGROWTH=5,
MAXSIZE=50
),
FILEGROUP FILEGROUP2(
NAME=examFile,
FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.SHALABYSQL\MSSQL\DATA\examFile.ndf',
SIZE=30,
FILEGROWTH=5,
MAXSIZE=50
)
LOG ON(
NAME=logFile,
FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.SHALABYSQL\MSSQL\DATA\logFile.ldf',
SIZE=5,
FILEGROWTH=5,
MAXSIZE=20
)

